### ISSUE TITLE
The elegant wyHyperLogLog

### ISSUE THREAD

**Issue by wangyi-fudan** [oertl/probminhash#1]
Dear oertl:
   I am Yi Wang the author of wyhash :-D  I polished the hyperloglog algorithm by discovering the underlying mathematical formules and constant. I improved reduced 1% log scale error compared to old versions. It is available at https://github.com/wangyi-fudan/wyhll
  Currently, I am interested in probabilistic skech methods and will learn advanced methods from your papers.

**Comment by oertl** [comment]
Hi Yi Wang, I replied with an email to the address given in your GitHub profile. I will close this issue as this is not related to ProbMinHash.
