### ISSUE TITLE
Question on OPH with optimal densification versus ProbMinHash

### ISSUE THREAD

**Issue by jianshu93** [oertl/probminhash#3]
Hello Otmar, 

In the main paper:

“OPH has by far the best performance for input sizes n which are in the order of m, but is quite slow for small n” (Figure 5. The last sub figure, when w_d is 1, probminhash will then be simple minhash and can be compare with OPH with optimal densification), this is exactly what the most recent bidirectional densification idea was solving (https://dl.acm.org/doi/abs/10.1145/3448016.3452833), e.g., when n is small and there will be many empty bins after hashing n element to the sketch with size m, optimal densification has an O(m^2) complexity for densification, which means it is very slow. bidensification improved it to O(m), so very fast then, at all size of n relative to m. In practice, n ls always much larger than m, so even for the original densification, no problem in the real-world application, but the bidirectional densification idea solves the problem with small n in the end. With the bidirectional densification, OPH with bidirectional densification is now strictly O(n+m) no matter the size of m and n. Do you think this is something interesting to implement or mention.

Thanks,

Jianshu

**Comment by oertl** [comment]
Hi Jianshu,

the non-streaming variants of ProbMinHash estimate a threshold in advance, and the points are computed only up to that threshold. If empty bins remain, the whole procedure is repeated with a larger threshold. Instead, one could apply densification, which is faster. However, densification also has a disadvantage. As shown in Fig. 4 in my paper, OPH can lead to a worse MSE than other approaches in some scenarios.

Best 

Otmar

**Comment by jianshu93** [comment]
Hello Otmar,

Any idea why in those cases, there is a larger RMSE for the densification idea. not 2-universal hash function so that the hashed values are not distributed evenly? the Bidirectional densification has a smaller variance than optional densification with respect to m (sketch size), could it improve the the RMSE a little bit. There is only a python reference implementation of the Bidirectional densification idea, so it takes times to compare the 2 densification idea. Ideally, densification idea should achieve the same variance with original minhash sqrt(J(1-j)/m) right. 

Thanks,

Jianshu

**Comment by oertl** [comment]
The densification schemes just copy values from nonempty bins. This does not really generate additional information which would improve the estimation of the Jaccard similarity as it is some kind of redundant information. So the effective sketch size is likely smaller than m leading to a larger variance.

Otmar

**Comment by jianshu93** [comment]
Ok sounds nice but if we use a much large m, compare to MinHash m, since it is very fast, e.g., when n is 10^6 or more, m can be 10^5 (so effective may be only 10^4), corresponding to a smaller m (10^4, a guess) in the Minhash case, we could achieve similar variance with MinHash, but not sacrificing speed since 10^6 + 10^5 is only 1.1X10^6. I am asking this because in the genomic case, n is alway very large, 10^6 to 10^7 while we only need a very small m, liken 10^4, we can then be accurate even for highly similar set. 

Jianshu

**Comment by oertl** [comment]
Yes, I assumed equal m. 

Maybe you are interested in this nonstreaming variant of SuperMinHash (https://github.com/dynatrace-oss/hash4j/blob/4e123cf09efe706d008dd6c471628e11337c6b98/src/main/java/com/dynatrace/hash4j/similarity/SuperMinHashPolicy_v1.java). I would be interested how its performance compares to the densification schemes.

Otmar

**Comment by jianshu93** [comment]
Hello Otmar,

Thanks, I will see what can do with this to compare.

Jianshu
